# Generated by Django 6.0.1 on 2026-10-03

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChallengeCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="DailyCheckIn",
            fields=[
                ("check_in_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("check_in_date", models.DateField(auto_now_add=True)),
                ("stress_level", models.CharField(choices=[("VERY_HIGH", "very high"), ("HIGH", "high"), ("MODERATE", "moderate"), ("VERY_LOW", "very low"), ("LOW", "low")], default="MODERATE", max_length=10)),
                ("energy_level", models.CharField(choices=[("VERY_HIGH", "very high"), ("HIGH", "high"), ("MODERATE", "moderate"), ("VERY_LOW", "very low"), ("LOW", "low")], default="MODERATE", max_length=10)),
                ("focus_level", models.CharField(choices=[("VERY_HIGH", "very high"), ("HIGH", "high"), ("MODERATE", "moderate"), ("LOW", "low"), ("VERY_LOW", "very low")], default="MODERATE", max_length=10)),
                ("mood", models.CharField(choices=[("HAPPY", "happy"), ("NEUTRAL", "neutral"), ("SAD", "sad"), ("ANXIOUS", "anxious")], default="HAPPY", max_length=10)),
                ("sleep_quality", models.CharField(choices=[("POOR", "poor"), ("FAIR", "fair"), ("GOOD", "good")], default="POOR", max_length=10)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="SubChallenge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("external_link", models.URLField(blank=True, null=True)),
                ("points", models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["-earned_at"]},
        ),
        migrations.CreateModel(
            name="UserChallenge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("IN_PROGRESS", "In Progress"), ("COMPLETED", "Completed")], default="IN_PROGRESS", max_length=12)),
                ("progress", models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserSubChallenge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Badge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                ("icon", models.ImageField(blank=True, null=True, upload_to="badges/")),
                ("points_required", models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ("is_active", models.BooleanField(default=True)),
                ("challenges_required", models.IntegerField(default=0)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(condition=models.Q(("points_required__gte", 0)), name="badge_points_required_nonnegative"),
                    models.CheckConstraint(condition=models.Q(("challenges_required__gte", 0)), name="badge_challenges_required_nonnegative"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Challenge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("points", models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0)])),
                ("duration", models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(1)])),
                ("is_active", models.BooleanField(default=True)),
                ("external_link", models.URLField(blank=True, null=True)),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="challenges", to="core.challengecategory")),
            ],
        ),
    ]
