# Generated by Django 6.0.1 on 2026-10-03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(model_name="dailycheckin", name="user", field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="daily_checkins", to=settings.AUTH_USER_MODEL)),
        migrations.AddField(model_name="subchallenge", name="challenge", field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sub_challenges", to="core.challenge")),
        migrations.AddField(model_name="userbadge", name="badge", field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="user_badges", to="core.badge")),
        migrations.AddField(model_name="userbadge", name="user", field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="user_badges", to=settings.AUTH_USER_MODEL)),
        migrations.AddField(model_name="userchallenge", name="challenge", field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="user_challenges", to="core.challenge")),
        migrations.AddField(model_name="userchallenge", name="user", field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="user_challenges", to=settings.AUTH_USER_MODEL)),
        migrations.AddField(model_name="usersubchallenge", name="sub_challenge", field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="user_sub_challenges", to="core.subchallenge")),
        migrations.AddField(model_name="usersubchallenge", name="user_challenge", field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="user_sub_challenges", to="core.userchallenge")),
        migrations.AddConstraint(model_name="challenge", constraint=models.CheckConstraint(condition=models.Q(("points__gte", 0)), name="challenge_points_nonnegative")),
        migrations.AddConstraint(model_name="challenge", constraint=models.CheckConstraint(condition=models.Q(("duration__gt", 0)), name="challenge_duration_positive")),
        migrations.AddConstraint(model_name="dailycheckin", constraint=models.UniqueConstraint(fields=("user", "check_in_date"), name="unique_daily_checkin_per_user")),
        migrations.AddConstraint(model_name="subchallenge", constraint=models.CheckConstraint(condition=models.Q(("points__gte", 0)), name="subchallenge_points_nonnegative")),
        migrations.AddConstraint(model_name="userbadge", constraint=models.UniqueConstraint(fields=("user", "badge"), name="unique_badge_per_user")),
        migrations.AddConstraint(model_name="userchallenge", constraint=models.UniqueConstraint(fields=("user", "challenge"), name="unique_challenge_per_user")),
        migrations.AddConstraint(model_name="userchallenge", constraint=models.CheckConstraint(condition=models.Q(("progress__gte", 0), ("progress__lte", 100)), name="user_challenge_progress_range")),
        migrations.AddConstraint(model_name="usersubchallenge", constraint=models.UniqueConstraint(fields=("user_challenge", "sub_challenge"), name="unique_subchallenge_per_user_challenge")),
    ]
