# Generated by Django 6.0.1 on 2026-01-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_badge_userbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='challenges_required',
            field=models.IntegerField(default=0),
        ),
    ]
