# Generated by Django 6.0.1 on 2026-01-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_badge_challenges_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailycheckin',
            name='energy_level',
            field=models.CharField(choices=[('VERY_HIGH', 'very high'), ('HIGH', 'high'), ('MODERATE', 'moderate'), ('VERY_LOW', 'very low'), ('LOW', 'low')], default='MODERATE', max_length=10),
        ),
        migrations.AlterField(
            model_name='dailycheckin',
            name='focus_level',
            field=models.CharField(choices=[('VERY_HIGH', 'very high'), ('HIGH', 'high'), ('MODERATE', 'moderate'), ('VERY_LOW', 'very low'), ('LOW', 'low')], default='MODERATE', max_length=10),
        ),
        migrations.AlterField(
            model_name='dailycheckin',
            name='stress_level',
            field=models.CharField(choices=[('VERY_HIGH', 'very high'), ('HIGH', 'high'), ('MODERATE', 'moderate'), ('VERY_LOW', 'very low'), ('LOW', 'low')], default='MODERATE', max_length=10),
        ),
    ]
