# Generated by Django 6.0.1 on 2026-10-03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("to", models.EmailField(max_length=254)),
                ("template", models.CharField(max_length=255)),
                ("subject", models.CharField(max_length=100)),
                ("context", models.JSONField(default=dict)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("send_attempts", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
            ],
            options={
                "indexes": [models.Index(fields=["to", "template"], name="notificatio_to_f68a82_idx")],
            },
        ),
    ]
