"""
Django settings for GamifiedStressApp project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import http
from datetime import timedelta
from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/
load_dotenv(os.path.join(BASE_DIR, '.env'))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = os.getenv("DEBUG", "False") == "True"

CSRF_TRUSTED_ORIGINS = ['http://127.0.0.1:9000']

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "").split(",")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
	"django.contrib.sites",
	'django_extensions',
    'rest_framework',
    'djoser',
    'user',
    'core',
	'notification',
	'accounts',
    'rest_framework_simplejwt',
	'rest_framework_simplejwt.token_blacklist',
	'dj_rest_auth',
	'dj_rest_auth.registration',
    'corsheaders',
	'django_celery_results',
	'allauth',
	'allauth.account',
	'allauth.socialaccount',
	'allauth.socialaccount.providers.google',
	'anymail',
]

SITE_ID = 1

AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
)

REST_FRAMEWORK = {
    'COERCE_DECIMAL_TO_STRING': False,
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    )
}

CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "http://localhost:9000",
    "http://127.0.0.1:8000",
    "http://127.0.0.1:9000",
]

MIDDLEWARE = [
	'corsheaders.middleware.CorsMiddleware',
	'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
	'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'GamifiedStressApp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'GamifiedStressApp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv("DB_NAME"),
        'USER': os.getenv("DB_USER"),
        'PASSWORD': os.getenv("DB_PASSWORD"),
        'HOST': os.getenv("DB_HOST"),
        'PORT': os.getenv("DB_PORT"),
    }
}

CORS_ORIGIN_ALLOW_ALL = True


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'user.User'

#allauth stuff
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]
ACCOUNT_EMAIL_VERIFICATION = "none"

#djoser template stuff
ACTIVATION_URL = "activate/{uid}/{token}"

DJOSER = {
	"LOGIN_FIELD": "email",
    "SOCIAL_AUTH_ALLOWED_REDIRECT_URIS": [
        "http://localhost:9000",
	    "http://127.0.0.1:9000",
    ],  #change this to frontend url when it's ready, change on Google cloud as well
    'USER_CREATE_PASSWORD_RETYPE': True,
    'SEND_ACTIVATION_EMAIL': True,
	"ACTIVATION_URL": "activate/{uid}/{token}",
	"EMAIL": {
        "activation": "notification.djoser.ActivationEmail",
        "confirmation": "notification.djoser.ConfirmationEmail",
        "password_reset": "notification.djoser.PasswordResetEmail",
    },
    'SERIALIZERS': {
        'user_create': 'user.serializers.UserCreateSerializer',
        'user': 'user.serializers.UserSerializer',
        'current_user': 'user.serializers.UserSerializer',
    }
}

REST_USE_JWT = True

REST_AUTH_TOKEN_MODEL = None

REST_AUTH = {
	"USE_JWT": True,
	"TOKEN_MODEL": None,
}

REST_AUTH_SERIALIZERS = {
    "JWT_SERIALIZER": "dj_rest_auth.serializers.JWTSerializer",
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=180),
	"REFRESH_TOKEN_LIFETIME": timedelta(days=365),
	"ROTATE_REFRESH_TOKENS": False,
	"BLACKLIST_AFTER_ROTATION": True,
}

#email stuff
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = os.getenv("EMAIL_PORT")
EMAIL_USE_TLS = True

EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")

DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")

#celery stuff
#message broker where redis gets tasks from
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL")

#where celery stores task results and states
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND")

#only accept JSON-serialized messages. a security and sanity choice
CELERY_ACCEPT_CONTENT = ["json"]

#serialize task payloads as JSON
CELERY_TASK_SERIALIZER = "json"

#serialize task results as JSON
CELERY_RESULT_SERIALIZER = "json"

#the Timezone celery uses for scheduling and timestamps
CELERY_TIMEZONE = "UTC"

#this forces celery to operate in UTC internally
CELERY_ENABLE_UTC = True

#workers ACKnowledge tasks AFTER they finish executing
#if a worker crashes mid-task, the task isn't lost and will be retried
CELERY_TASK_ACKS_LATE = True

#if a worker process dies while executing, tell the broker to put the task back on the queue
CELERY_TASK_REJECT_ON_WORKER_LOST = True

#how many tasks a worker prefetches at once
#setting this to 1 prevents a single worker from hoarding tasks in memory
CELERY_WORKER_PREFETCH_MULTIPLIER = 1

#hard time limit for a task. If a task runs longer than this, it is killed by force
CELERY_TASK_TIME_LIMIT = 60*60

#soft time limit for a task, meaning celery raises a SoftTimeLimitExceeded exception first
#this giving your task a chance to clean up before being killed
CELERY_TASK_SOFT_TIME_LIMIT = 60*55

#this is for redis, it controls how long a task can run
CELERY_BROKER_TRANSPORT_OPTIONS = {"visibility_timeout": 60*60*2}

#this controls how long task results are kept in the result backend
CELERY_RESULT_EXPIRES = 60*60

#retry connecting to the broker on startup instead of crashing immediately
#important if using Docker
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

#tracks when a task transitions to the "STARTED" state
CELERY_TASK_TRACK_STARTED = True

SOCIALACCOUNT_ONLY = True

SOCIALACCOUNT_ADAPTER = "accounts.adapters.SocialAccountAdapter"

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        # For each OAuth based provider, either add a ``SocialApp``
        # (``socialaccount`` app) containing the required client
        # credentials, or list them here:
        "APPS": [
            {
                "client_id": os.getenv("GOOGLE_CLIENT_ID"),
                "secret": os.getenv("GOOGLE_CLIENT_SECRET"),
                "key": "",
                "settings": {
                    # You can fine tune these settings per app:
                    "scope": [
                        "profile",
                        "email",
	                    "openid",
                    ],
                    "auth_params": {
                        "access_type": "online",
                    },
                },
            },
        ],
        # The following provider-specific settings will be used for all apps:
        "SCOPE": [
            "profile",
            "email",
	        "openid",
        ],
        "AUTH_PARAMS": {
            "access_type": "online",
        },
    }
}