# Generated by Django 6.0.1 on 2026-01-16 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'student'), ('WORKER', 'worker'), ('INDIVIDUAL', 'Individual')], default='STUDENT', max_length=20),
        ),
    ]
