# Generated by Django 6.0.1 on 2026-01-19 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
